version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: vcci_member
      POSTGRES_PASSWORD: vcciMember2025
      POSTGRES_DB: vcci_member
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vcci@gmail.com
      PGADMIN_DEFAULT_PASSWORD: vcci!#2025
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
